# Usar imagen oficial de Tomcat con JDK 17 
FROM tomcat:jre17-temurin 
# Eliminar aplicaciones por defecto 
RUN rm -rf /usr/local/tomcat/webapps/* 
# Copiar la aplicación 
COPY ./sitio-web /usr/local/tomcat/webapps/ROOT 
# Exponer puerto 
EXPOSE 8080 
# Comando por defecto 
CMD ["catalina.sh", "run"]